# theme: minima
# theme-repo: https://github.com/jekyll/minima/tree/master

title: Brendan Reardon

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%Y-%m-%d"

header_pages:
  - about.md

sass:
  quiet_deps: true
